title: a chemical engineer's notebook
description: this is where I post random notebooks where I noodle around with code and work through examples of engineering problems and how to solve them
github_username: selenized

timezone: America/Edmonton

permalink: /:year/:month/:day/:title/

include: _pages

exclude: _notebooks

use_math: true

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: mint
search: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false

feed:
  excerpt_only: true

author:
  name   : "allan"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "I'm chemical engineer living in Edmonton, Alberta, Canada. My interests tend towards process safety and hazard analysis."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/selenized"


footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/selenized/selenized.github.io"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

comments:
  provider: "disqus"
  disqus:
    shortname: "selenizeds"

